config/routes.rb
Rails.application.routes.draw do

  root 'causes#index'
  resources :causes do
    resources :donations, shallow: true
  end
  get '/payment_confirmation', to: 'donations#confirmation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cause.rb
class Cause < ApplicationRecord
  has_many :donations
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :cause
  validates :amount, presence: true

  def report_dgp_conversion
    if Rails.env == "production"
      url = "https://dogoodpoints.herokuapp.com/api/conversions"
      secret = Rails.application.credentials.dgp_secret
    else
      url = 'http://localhost:3000/api/conversions'
      secret = 'oX7qB4nY3IwFjMHws1au'
    end

    RestClient.post(url, { engagement_id: external_id, amount: amount },
                          { "Authorization" => "Token #{secret}" })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  before_action :set_cause, only: [:show, :edit, :update, :destroy]

  # GET /causes
  # GET /causes.json
  def index
    @causes = Cause.all
  end

  # GET /causes/1
  # GET /causes/1.json
  def show
    @source = params[:source]
    @external_id = params[:engagement_id]
  end

  # GET /causes/new
  def new
    @cause = Cause.new
  end

  # GET /causes/1/edit
  def edit
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = Cause.new(cause_params)

    respond_to do |format|
      if @cause.save
        format.html { redirect_to @cause, notice: 'Cause was successfully created.' }
        format.json { render :show, status: :created, location: @cause }
      else
        format.html { render :new }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /causes/1
  # PATCH/PUT /causes/1.json
  def update
    respond_to do |format|
      if @cause.update(cause_params)
        format.html { redirect_to @cause, notice: 'Cause was successfully updated.' }
        format.json { render :show, status: :ok, location: @cause }
      else
        format.html { render :edit }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause.destroy
    respond_to do |format|
      format.html { redirect_to causes_url, notice: 'Cause was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cause
      @cause = Cause.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cause_params
      params.require(:cause).permit(:name)
    end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_cause, only: [:show, :edit, :update, :destroy]

  def index
    @donations = Donation.all
  end

  def new
    @cause = Cause.find(params[:cause_id])
    @donation = @cause.donations.new
  end

  def create
    @cause = Cause.find(params[:cause_id])
    @donation = @cause.donations.new(donation_params)
    if @donation.save
      #report conversion on half of the causes to test pixel-only integration
      # API call for Even-numbered offers
      if @cause.id % 2 == 0
        report_conversion(@donation)
        redirect_to root_path
      else
        redirect_to '/payment_confirmation'
      end
    else
      render 'new'
    end
  end

  def confirmation
  end

  def destroy
  end

  private

  def set_cause
    @donation = Donation.find(params[:id])
  end

  def donation_params
    params.require(:donation).permit(:full_name, :email, :postal_code, :amount, :source, :external_id )
  end

  #adapter for reporting to traffic source platforms
  def report_conversion(donation)
    if donation.source == 'dgp'
      donation.report_dgp_conversion
    elsif donation.source == 'swagbucks'
      #report_swagbucks_conversion(donation)
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  def pixel_tag
    if Rails.env == 'production'
      domain = 'https://dogoodpoints.herokuapp.com'
      client_key =  Rails.application.credentials.dgp_client_key
    else
      domain = 'http://localhost:3000'
      client_key = 'XxAZecFtTNNOjg'
    end
    tag(:image,
        src: "#{domain}/track?client_key=#{client_key}",
        style: "display: none;")
  end
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/views/causes/_form.html.erb
<%= form_with(model: cause, local: true) do |form| %>
  <% if cause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cause.errors.count, "error") %> prohibited this cause from being saved:</h2>

      <ul>
      <% cause.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/causes/edit.html.erb
<h1>Editing Cause</h1>

<%= render 'form', cause: @cause %>

<%= link_to 'Show', @cause %> |
<%= link_to 'Back', causes_path %>

app/views/causes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Causes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @causes.each do |cause| %>
      <tr>
        <td><%= cause.name %></td>
        <td><%= link_to 'Show', cause %></td>
        <td><%= link_to 'Edit', edit_cause_path(cause) %></td>
        <td><%= link_to 'Destroy', cause, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cause', new_cause_path %>

app/views/causes/new.html.erb
<h1>New Cause</h1>

<%= render 'form', cause: @cause %>

<%= link_to 'Back', causes_path %>

app/views/causes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cause.name %>
</p>

<%= link_to 'donate', new_cause_donation_path(
    @cause, params.permit!.to_hash.slice("source", "engagement_id")) %>
<%= link_to 'Edit', edit_cause_path(@cause) %> |
<%= link_to 'Back', causes_path %>

app/views/donations/confirmation.html.erb
<%= pixel_tag %>
<h2>Thank you for your payment!</h2>

app/views/donations/new.html.erb
<h4>Donate to <%= @cause.name %></h4>

<%= form_for([@cause, @donation]) do |f| %>
  <%= f.label :full_name %>
  <%= f.text_field :full_name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :postal_code %>
  <%= f.text_field :postal_code %>
  <%= f.label :amount %>
  <%= f.number_field :amount %>
  <%= f.hidden_field :source, value: params[:source] %>
  <%= f.hidden_field :external_id, value: params[:engagement_id] %>
  <div>
    <br><%= f.submit "Donate" %>
  </div>
  <div>
    <br><%= link_to 'Back', cause_path(@cause) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>DGP Foundation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>